package constantly

func writeConstants() {
	refreshPreview()
	saveToFile(false) //false that its json
}

func previewString() string {
	var result = "// File generated by constantly\n\npackage " + AppData.pkg.Text
	if !goType() {
		u := AppData.userEntries.underlying.Text
		if u == "" {
			u = AppData.userEntries.underlying.PlaceHolder
		}
		result += "\n\ntype " + AppData.userEntries.consType.Text + " " + u
	}
	result += "\n\nconst (\n"
	for i := 0; i < AppData.rows; i++ {
		result += makeLineFromTab(i) + "\n"
	}
	result += ")\n"

	if AppData.userEntries.genStr.Checked {
		result += genStrFuncs()
	}

	if AppData.userEntries.genAssoc.Checked {
		result += genAssocFuncs()
	}

	return result
}

func refreshPreview() {
	AppData.preview.SetText(previewString())
}

func makeLineFromTab(row int) string {
	var comment string
	line := "\t"
	value := AppData.userEntries.cell(Value, row)
	assign := ""

	if len(value) > 0 {
		assign = " = "
	}

	if AppData.userEntries.genComment.Checked {
		comment += "\t// " + AppData.userEntries.cell(Assoc, row)
	}

	line += AppData.userEntries.cell(Prefix, row) + AppData.userEntries.cell(BaseID, row) + AppData.userEntries.cell(Suffix, row)
	line += " " + AppData.userEntries.cell(Type, row) + assign + value

	if len(comment) > 0 {
		line = comment + "\n" + line
	}

	return line
}

func genStrFuncs() string {
	var result string
	if AppData.userEntries.genStr.Checked {
		result = "\nfunc ConstString(c " + AppData.userEntries.consType.Text + ") string {\n"
		result += "\tswitch c {\n\t"
		for i := 0; i < AppData.rows; i++ {
			name := AppData.userEntries.cell(Prefix, i) + AppData.userEntries.cell(BaseID, i) + AppData.userEntries.cell(Suffix, i)
			result += "case " + name + ":\n\t\t"
			result += `return "` + name + "\"\n\t"
		}
		result += "}\n\treturn \"\"\n}\n"
	}
	return result
}

func genAssocFuncs() string {
	var result string
	if AppData.userEntries.genStr.Checked {
		result = "\nfunc AssocString(c " + AppData.userEntries.consType.Text + ") string {\n"
		result += "\tswitch c {\n\t"
		for i := 0; i < AppData.rows; i++ {
			name := AppData.userEntries.cell(Prefix, i) + AppData.userEntries.cell(BaseID, i) + AppData.userEntries.cell(Suffix, i)
			result += "case " + name + ":\n\t\t"
			result += `return "` + AppData.userEntries.cell(Assoc, i) + "\"\n\t"
		}
		result += "}\n\treturn \"\"\n}\n"
	}
	return result
}

func goType() bool {
	t := AppData.userEntries.consType.Text
	// do not use placeholder. if user did not input anything in
	// the type box then assume these are string constants
	switch t {
	case "", "bool", "string",
		"byte", "int8", "uint8",
		"int16", "uint16",
		"int", "uint", "int32", "uint32",
		"int64", "uint64",
		"float32", "float64",
		"complex64", "complex128":
		return true
	}
	return false
}
